bind_address = "0.0.0.0:8081"
log_level = 0
opentelemetry = "http://jaeger:4317"

[database]
path = "database/backend.sqlite"
salt = "be sure to change it"

[[judger]]
name = "http://judger:8080"
type = "static"

[grpc]

[imgur]
client_id = "fffffffffffffff"
client_secret = "ffffffffffffffffffffffffffffffffffffffff"
