log_level = 2

[runtime]
temp = ".temp"
bind = "0.0.0.0:8080"
accuracy = 50000
root_cgroup = "mdoj/c."

[platform]
cpu_time_multiplier = 1.0
available_memory = 1073741824
output_limit = 33554432

[nsjail]
runtime = "./nsjail-3.1"
rootless = false
log = "/dev/null"
cgroup_version = "v2"

[plugin]
path = "plugins"

[kernel]
kernel_hz = 1000
tickless = false
